name       : breeze-icons
version    : 5.35.0
release    : 4
source     :
    - https://download.kde.org/stable/frameworks/5.35/breeze-icons-5.35.0.tar.xz : 3ccc2373acf345f867e085bafa522906d4c97a198a88c4fab0b42b8b08d93b02
license    : LGPL-3.0
component  : desktop.theme
summary    : Breeze icon theme
description: |
    Breeze-icons is a freedesktop.org compatible icon theme.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
