name       : breeze-icons
version    : 5.48.0
release    : 17
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.48/breeze-icons-5.48.0.tar.xz : 10fb18b3ab1cc8991054bd984f70e0f966dd41f4d2d2743cc4e09aef7ace13dc
license    : LGPL-3.0
component  : desktop.theme
summary    : Breeze icon theme
description: |
    Breeze-icons is a freedesktop.org compatible icon theme.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Re-use icon for Doflicky
    ln -s /usr/share/icons/breeze/devices/64/cpu.svg $installdir/usr/share/icons/breeze/apps/48/jockey.svg
    ln -s /usr/share/icons/breeze-dark/devices/64/cpu.svg $installdir/usr/share/icons/breeze-dark/apps/48/jockey.svg
