name       : breeze-icons
version    : 5.79.0
release    : 50
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.79/breeze-icons-5.79.0.tar.xz : c6320406a8e93df3a5918e24ef94b76b3c0ddd3e17567451b7dce403f33b4d1b
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-3.0-or-later # dialog-information-symbolic from Papirus
    - LGPL-3.0-or-later # Breeze
component  : desktop.theme
summary    : Breeze icon theme
description: |
    Breeze-icons is a freedesktop.org compatible icon theme.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - python-lxml
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Re-use icon for Doflicky
    ln -s /usr/share/icons/breeze/devices/64/cpu.svg $installdir/usr/share/icons/breeze/apps/48/jockey.svg
    ln -s /usr/share/icons/breeze-dark/devices/64/cpu.svg $installdir/usr/share/icons/breeze-dark/apps/48/jockey.svg
    # Required for Solus-SC. From Papirus.
    install -Dm00644 $pkgfiles/dialog-information-symbolic.svg $installdir/usr/share/icons/breeze/status/symbolic/dialog-information-symbolic.svg
