name       : breeze-icons
version    : 5.63.0
release    : 33
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.63/breeze-icons-5.63.0.tar.xz : 25a5b55e5be0fc3df837e0dd8f6721bfcbb30ed94be6ac92c88523485ba2719e
license    :
    - GPL-3.0-or-later # dialog-information-symbolic from Papirus
    - LGPL-3.0-or-later # Breeze
component  : desktop.theme
summary    : Breeze icon theme
description: |
    Breeze-icons is a freedesktop.org compatible icon theme.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Re-use icon for Doflicky
    ln -s /usr/share/icons/breeze/devices/64/cpu.svg $installdir/usr/share/icons/breeze/apps/48/jockey.svg
    ln -s /usr/share/icons/breeze-dark/devices/64/cpu.svg $installdir/usr/share/icons/breeze-dark/apps/48/jockey.svg
    # Required for Solus-SC. From Papirus.
    install -Dm00644 $pkgfiles/dialog-information-symbolic.svg $installdir/usr/share/icons/breeze/status/symbolic/dialog-information-symbolic.svg
