name       : breeze-icons
version    : 5.38.0
release    : 6
source     :
    - https://download.kde.org/stable/frameworks/5.38/breeze-icons-5.38.0.tar.xz : 89291dd396bd0f42e9b90eb92f46895fa461ebc2b420a58c663e0c4898894e25
license    : LGPL-3.0
component  : desktop.theme
summary    : Breeze icon theme
description: |
    Breeze-icons is a freedesktop.org compatible icon theme.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
