name       : breeze-icons
version    : 5.28.0
release    : 2
source     :
    - http://download.kde.org/stable/frameworks/5.28/breeze-icons-5.28.0.tar.xz : 02fa95a016cf8ae72a8ea7003fa480194d1d347245f7a7bb61ea94009e78fc1b
license    : LGPL-3.0
component  : desktop.theme
summary    : Breeze icon theme
description: |
    Breeze-icons is a freedesktop.org compatible icon theme.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
