name       : breeze-icons
version    : 5.40.0
release    : 9
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.40/breeze-icons-5.40.0.tar.xz : 26e1f958a2ed4c4622525e92aec2df582822e44db151f51ac8701995b8d9b7bd
license    : LGPL-3.0
component  : desktop.theme
summary    : Breeze icon theme
description: |
    Breeze-icons is a freedesktop.org compatible icon theme.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install

    # Re-use icon for Doflicky
    ln -s /usr/share/icons/breeze/devices/64/cpu.svg $installdir/usr/share/icons/breeze/apps/48/jockey.svg
    ln -s /usr/share/icons/breeze-dark/devices/64/cpu.svg $installdir/usr/share/icons/breeze-dark/apps/48/jockey.svg
