name       : breeze-icons
version    : 5.60.0
release    : 30
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.60/breeze-icons-5.60.0.tar.xz : 99d0cbda6a38766079166633a06493929222c6443e8718c1a2db4aeb5b5f20b7
license    :
    - GPL-3.0-or-later # dialog-information-symbolic from Papirus
    - LGPL-3.0-or-later # Breeze
component  : desktop.theme
summary    : Breeze icon theme
description: |
    Breeze-icons is a freedesktop.org compatible icon theme.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Re-use icon for Doflicky
    ln -s /usr/share/icons/breeze/devices/64/cpu.svg $installdir/usr/share/icons/breeze/apps/48/jockey.svg
    ln -s /usr/share/icons/breeze-dark/devices/64/cpu.svg $installdir/usr/share/icons/breeze-dark/apps/48/jockey.svg
    # Required for Solus-SC. From Papirus.
    install -Dm00644 $pkgfiles/dialog-information-symbolic.svg $installdir/usr/share/icons/breeze/status/symbolic/dialog-information-symbolic.svg
