name       : breeze-icons
version    : 5.53.0
release    : 22
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.53/breeze-icons-5.53.0.tar.xz : aeb1c147102959838427a47ebbcae07e33779b64dbede66fe143db5c419e2298
license    : LGPL-3.0-or-later
component  : desktop.theme
summary    : Breeze icon theme
description: |
    Breeze-icons is a freedesktop.org compatible icon theme.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Re-use icon for Doflicky
    ln -s /usr/share/icons/breeze/devices/64/cpu.svg $installdir/usr/share/icons/breeze/apps/48/jockey.svg
    ln -s /usr/share/icons/breeze-dark/devices/64/cpu.svg $installdir/usr/share/icons/breeze-dark/apps/48/jockey.svg
