name       : breeze-icons
version    : 5.42.0
release    : 11
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.42/breeze-icons-5.42.0.tar.xz : 99900eb0d2c9b5822e93f6be21fcf4581919c94cc02f8c9331de7921c0023257
license    : LGPL-3.0
component  : desktop.theme
summary    : Breeze icon theme
description: |
    Breeze-icons is a freedesktop.org compatible icon theme.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install

    # Re-use icon for Doflicky
    ln -s /usr/share/icons/breeze/devices/64/cpu.svg $installdir/usr/share/icons/breeze/apps/48/jockey.svg
    ln -s /usr/share/icons/breeze-dark/devices/64/cpu.svg $installdir/usr/share/icons/breeze-dark/apps/48/jockey.svg
