name       : breeze-icons
version    : 5.39.0
release    : 8
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.39/breeze-icons-5.39.0.tar.xz : bd4077f88d106f7dcdefd8f260edbee597e72572e17f443ccd10d3a0eabb4b8c
license    : LGPL-3.0
component  : desktop.theme
summary    : Breeze icon theme
description: |
    Breeze-icons is a freedesktop.org compatible icon theme.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install

    # Re-use icon for Doflicky
    ln -s /usr/share/icons/breeze/devices/64/cpu.svg $installdir/usr/share/icons/breeze/apps/48/jockey.svg
    ln -s /usr/share/icons/breeze-dark/devices/64/cpu.svg $installdir/usr/share/icons/breeze-dark/apps/48/jockey.svg
