name       : breeze-icons
version    : 5.25.0
release    : 1
source     :
    - https://github.com/KDE/breeze-icons/archive/v5.25.0.tar.gz : eb9337484165a2cd5a5b5f5cdae8fdb3a5883f7d2ee7732606c9e2a3559edde2
license    : LGPL-3.0
component  : desktop.theme
summary    : Breeze icon theme
description: |
    Breeze-icons is a freedesktop.org compatible icon theme.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
