name       : breeze-icons
version    : 5.46.0
release    : 15
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.46/breeze-icons-5.46.0.tar.xz : 830c738605a4bc461d655fd3e0f66ec06a25cdf136910bc6a83f304c199007eb
license    : LGPL-3.0
component  : desktop.theme
summary    : Breeze icon theme
description: |
    Breeze-icons is a freedesktop.org compatible icon theme.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Re-use icon for Doflicky
    ln -s /usr/share/icons/breeze/devices/64/cpu.svg $installdir/usr/share/icons/breeze/apps/48/jockey.svg
    ln -s /usr/share/icons/breeze-dark/devices/64/cpu.svg $installdir/usr/share/icons/breeze-dark/apps/48/jockey.svg
